# Generated by Django 6.0.6 on 2026-07-01 00:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('destinos', '0002_initial'),
        ('grupos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='grupoexpedicao',
            name='criador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos_criados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='grupoexpedicao',
            name='destino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos', to='destinos.destino'),
        ),
        migrations.AddField(
            model_name='grupoexpedicao',
            name='membros',
            field=models.ManyToManyField(blank=True, related_name='grupos_participando', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pontoencontro',
            name='criador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pontos_criados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pontoencontro',
            name='destino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pontos_encontro', to='destinos.destino'),
        ),
        migrations.AddField(
            model_name='pontoencontro',
            name='grupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pontos_encontro', to='grupos.grupoexpedicao'),
        ),
    ]
