# Generated by Django 6.0.6 on 2026-07-01 00:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('destinos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('avaliou', 'Avaliou um destino'), ('comentou', 'Comentou em um destino'), ('entrou_grupo', 'Entrou em um grupo'), ('favoritou', 'Favoritou um destino'), ('cadastrou_destino', 'Cadastrou um destino'), ('criou_grupo', 'Criou um grupo de expedição'), ('seguiu', 'Passou a seguir')], max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='destinos.destino')),
            ],
            options={
                'verbose_name': 'Atividade',
                'verbose_name_plural': 'Atividades',
                'ordering': ['-created_at'],
            },
        ),
    ]
